# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='level',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
