# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biota', '0002_auto_20160409_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
