# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biota', '0006_auto_20160411_2117'),
        ('records', '0002_croprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biota.ScientificName')),
            ],
        ),
        migrations.RemoveField(
            model_name='bedset',
            name='site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='location_ptr',
        ),
        migrations.RemoveField(
            model_name='croprecord',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='croprecord',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date of propagation for production'),
        ),
        migrations.DeleteModel(
            name='BedSet',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
