# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0006_croprecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bed_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.BedSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date of propagation for production')),
                ('bed_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.BedSet')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date of propagation for production')),
                ('bed_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.BedSet')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Crop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NurseryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date of propagation for production')),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Crop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeederRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EW', 'Earthway'), ('GL', 'Glasser'), ('JANG', 'Jang')], max_length=2)),
                ('seeder_settings', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='croprecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='CropRecord',
        ),
        migrations.AddField(
            model_name='bedrecord',
            name='nursery_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.NurseryRecord'),
        ),
        migrations.AddField(
            model_name='bedrecord',
            name='seeder_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.SeederRecord'),
        ),
        migrations.AddField(
            model_name='bedrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
