# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biota', '0006_auto_20160411_2117'),
        ('records', '0007_auto_20160411_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_crop_name', models.CharField(max_length=100, null=True)),
                ('common_variety_name', models.CharField(max_length=100, null=True)),
                ('scientific_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biota.ScientificName')),
            ],
        ),
        migrations.RenameField(
            model_name='block',
            old_name='bed_set',
            new_name='beds',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='bed_set',
        ),
        migrations.RemoveField(
            model_name='bedrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='harvestrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurseryrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='site',
            name='area',
        ),
        migrations.AddField(
            model_name='bedset',
            name='beds',
            field=models.ManyToManyField(to='records.Bed'),
        ),
        migrations.AddField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seed',
            name='varieties',
            field=models.ManyToManyField(to='records.Variety'),
        ),
        migrations.AddField(
            model_name='crop',
            name='seeds',
            field=models.ManyToManyField(null=True, to='records.Seed'),
        ),
    ]
