# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20160411_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='seeds',
            field=models.ManyToManyField(to='records.Seed'),
        ),
    ]
