# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biota', '0006_auto_20160411_2117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0010_auto_20160412_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.CropGroup')),
                ('scientific_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biota.ScientificName')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='variety',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='variety',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='seeds',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='varieties',
        ),
        migrations.AddField(
            model_name='crop',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Seed'),
        ),
        migrations.AddField(
            model_name='seed',
            name='packet_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
        migrations.AddField(
            model_name='product',
            name='crops',
            field=models.ManyToManyField(to='records.Crop'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='varieties',
            field=models.ManyToManyField(to='records.Seed'),
        ),
    ]
